apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trip-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KORgosu/trip-currency-local.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: trip-service-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
